// Generated by CoffeeScript 1.3.3
(function() {
  var head, initializeWidget, script;

  if (typeof jQuery === "undefined") {
    script = document.createElement("script");
    script.src = "http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js";
    head = document.getElementsByTagName("head")[0];
    head.appendChild(script);
    script.onload = function() {
      return jQuery(function($) {
        return initializeWidget();
      });
    };
  } else {
    jQuery(function($) {
      return initializeWidget();
    });
  }

  initializeWidget = function() {
    var ovrCss, registrationLinks;
    ovrCss = document.createElement("link");
    ovrCss.href = 'https://s3.amazonaws.com/register2.rockthevote.com/widgetloader/css/style.css';
    ovrCss.rel = "stylesheet";
    ovrCss.type = "text/css";
    head = document.getElementsByTagName("head")[0];
    head.appendChild(ovrCss);
    registrationLinks = $('.floatbox[href*="register.rockthevote.com"],.floatbox[href*="register2.rockthevote.com"]');
    return registrationLinks.on('click', function(e) {
      var $body, $close, $container, $el, $iframe, $overlay;
      e.preventDefault();
      $el = $(this);
      $body = $('body');
      $overlay = $('<div class="ovr-overlay" />');
      $iframe = $('<iframe id="ovr-widget" />');
      $close = $('<a href="#" class="ovr-close">close [x]</a>');
      $container = $('<div id="ovr-container" />');
      $iframe.attr('src', $el.attr('href'));
      $body.append($container);
      $container.append($overlay);
      $overlay.hide().fadeIn(300);
      $container.append($iframe);
      $container.prepend($close);
      return $close.on('click', function(e) {
        var close;
        e.preventDefault();
        close = confirm("Close voter registration application?");
        if (close) {
          return $('.ovr-overlay, #ovr-container').remove();
        } else {
          return false;
        }
      });
    });
  };

}).call(this);
